DROP TABLE O_ORG;

CREATE TABLE O_ORG
(
   ORG_ID               NUMERIC(18)            NOT NULL,
   PARENT_ORG_ID        NUMERIC(18),
   ORG_NAME             VARCHAR(128)           NOT NULL,
   ORG_CODE             VARCHAR(20),
   ORG_ADDRESS          VARCHAR(128),
   ORG_SEQ              VARCHAR(512),
   CONSTRAINT PK_O_ORG PRIMARY KEY (ORG_ID)
);

ALTER TABLE O_ORG
   ADD CONSTRAINT FK_O_ORG_REFERE FOREIGN KEY (PARENT_ORG_ID)
      REFERENCES O_ORG (ORG_ID)
      ;

ALTER TABLE O_OPERATOR
   ADD CONSTRAINT FK_O_USER_REFER FOREIGN KEY (ORG_ID)
      REFERENCES O_ORG (ORG_ID)
      ;


INSERT INTO O_ORG ( ORG_ID, PARENT_ORG_ID, ORG_NAME, ORG_CODE, ORG_ADDRESS, ORG_SEQ ) VALUES ( 1001, NULL, 'Head Office', 'head', 'shanghai', '.1001.'); 
INSERT INTO O_ORG ( ORG_ID, PARENT_ORG_ID, ORG_NAME, ORG_CODE, ORG_ADDRESS, ORG_SEQ ) VALUES ( 1002, 1001, 'the sub company of shanghai', 'shanghai', 'pudong', '.1001.1002.'); 
INSERT INTO O_ORG ( ORG_ID, PARENT_ORG_ID, ORG_NAME, ORG_CODE, ORG_ADDRESS, ORG_SEQ ) VALUES ( 1003, 1001, 'the sub company of beijing', 'beijing', 'beijing', '.1001.1003.'); 
INSERT INTO O_ORG ( ORG_ID, PARENT_ORG_ID, ORG_NAME, ORG_CODE, ORG_ADDRESS, ORG_SEQ ) VALUES ( 1004, 1002, 'the R&D center of pudong', 'rd', 'pudong', '.1001.1004.'); 

