
CREATE TABLE O_CONTACTS
(
   CONTACT_ID           NUMERIC(18)            NOT NULL,
   OPERATOR_ID          NUMERIC(18),
   CONTACT_NAME         VARCHAR(20)            NOT NULL,
   RELATION             VARCHAR(20),
   PHONE                VARCHAR(20),
   POSTCODE             CHAR(6),
   ADDRESS              VARCHAR(128),
   EMAIL                VARCHAR(128),
   CONSTRAINT PK_O_CONTACTS PRIMARY KEY (CONTACT_ID)
);

ALTER TABLE O_CONTACTS
   ADD CONSTRAINT FK_O_CONTAC_REF FOREIGN KEY (OPERATOR_ID)
      REFERENCES O_OPERATOR (OPERATOR_ID)
      ON DELETE NO ACTION ON UPDATE RESTRICT;
